#-------------------------------------------------------------------------------
# Simple make file for example project: Hello world
# Created by Carmelo J. Fdez-Agüera Tortosa (a.k.a. Technik)
# On 2014-10-31
#-------------------------------------------------------------------------------
PRJ_NAME=shaderToy

REVSDK_HOME ?= ../..

include $(REVSDK_HOME)/common/linux/binary.mk

