#-----------------------------------------------------------------------------------------------------------------------
# Revolution SDK
# Created by Carmelo J. Fdez-Agüera Tortosa (a.k.a. Technik)
# On October 7th, 2012
#-----------------------------------------------------------------------------------------------------------------------
# Core module, make file

# Project configuration variables
MODULE_NAME := revcore

# -- Folder structure --
ROOT_DIR := ../../..
SRC_DIR := $(ROOT_DIR)/src
CODE_DIR := $(SRC_DIR)
OUT_DIR := $(ROOT_DIR)/bin/arduino

include $(REVSDK_HOME)/common/arduino/make/arduino-common.mk
include $(REVSDK_HOME)/common/arduino/make/module-common.mk